learning_templates/basic_app/urls.py
from django.urls import re_path, path
from basic_app import views

# Template Tagging
app_name = 'basic_app'

urlpatterns=[
    re_path(r'^relative/$', views.relative, name = 'relative'),
    re_path(r'^other/$', views.other, name = 'other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,re_path, include
from basic_app import views

urlpatterns = [
    re_path(r'^$',views.index,name = 'index'),
    re_path(r'^basic_app/', include('basic_app.urls')),
    re_path(r'^admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict ={'text':'Hello World','number':100}
    return render(request,'basic_app/index.html', context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class = "container">
        <ul class = "nav navbar-nav">
          <li ><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative Urls</a></li>
        </ul>
      </div>
    </nav>
    <div class = "container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load basic_app_extras %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    <!--<h2>This is Index.html page being shown</h2>-->
    <h1>{{ text|lower|chop:"world" }}</h1>
    <h1>{{ number|add:"157" }}</h1>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

learning_templates/templates/basic_app/relative_url.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
      <h1>Welcome to relative urls templates</h1>
      <a href="{% url 'basic_app:other' %}">Other Page</a><br>
      <a href="{% url 'admin:index' %}">Admin</a><br>
      <a href="{% url 'index' %}">Index</a>
  {% endblock %}